### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by boredsquirrel** [boredsquirrel/Linux#3]
- [ ] document polkit rules
- [ ] refer to hardening doc
  - [ ] include hardened polkit rules
  - [ ] include secureblue configs
  - [ ] selinux tricks
  - [ ] confined user
- [ ] update!
